/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRoutesRouteRouteImport } from './routes/(public-routes)/route'
import { Route as privateRoutesRouteRouteImport } from './routes/(private-routes)/route'
import { Route as publicRoutesIndexRouteImport } from './routes/(public-routes)/index'
import { Route as privateRoutesProfileIndexRouteImport } from './routes/(private-routes)/profile/index'
import { Route as privateRoutesAnalysesIndexRouteImport } from './routes/(private-routes)/analyses/index'
import { Route as privateRoutesAnalysesAnalysisIdRouteImport } from './routes/(private-routes)/analyses/$analysisId'
import { Route as authRoutesAuthRegisterRouteImport } from './routes/(auth-routes)/auth/register'
import { Route as authRoutesAuthLoginRouteImport } from './routes/(auth-routes)/auth/login'

const publicRoutesRouteRoute = publicRoutesRouteRouteImport.update({
  id: '/(public-routes)',
  getParentRoute: () => rootRouteImport,
} as any)
const privateRoutesRouteRoute = privateRoutesRouteRouteImport.update({
  id: '/(private-routes)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRoutesIndexRoute = publicRoutesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRoutesRouteRoute,
} as any)
const privateRoutesProfileIndexRoute =
  privateRoutesProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => privateRoutesRouteRoute,
  } as any)
const privateRoutesAnalysesIndexRoute =
  privateRoutesAnalysesIndexRouteImport.update({
    id: '/analyses/',
    path: '/analyses/',
    getParentRoute: () => privateRoutesRouteRoute,
  } as any)
const privateRoutesAnalysesAnalysisIdRoute =
  privateRoutesAnalysesAnalysisIdRouteImport.update({
    id: '/analyses/$analysisId',
    path: '/analyses/$analysisId',
    getParentRoute: () => privateRoutesRouteRoute,
  } as any)
const authRoutesAuthRegisterRoute = authRoutesAuthRegisterRouteImport.update({
  id: '/(auth-routes)/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authRoutesAuthLoginRoute = authRoutesAuthLoginRouteImport.update({
  id: '/(auth-routes)/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof publicRoutesIndexRoute
  '/auth/login': typeof authRoutesAuthLoginRoute
  '/auth/register': typeof authRoutesAuthRegisterRoute
  '/analyses/$analysisId': typeof privateRoutesAnalysesAnalysisIdRoute
  '/analyses': typeof privateRoutesAnalysesIndexRoute
  '/profile': typeof privateRoutesProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicRoutesIndexRoute
  '/auth/login': typeof authRoutesAuthLoginRoute
  '/auth/register': typeof authRoutesAuthRegisterRoute
  '/analyses/$analysisId': typeof privateRoutesAnalysesAnalysisIdRoute
  '/analyses': typeof privateRoutesAnalysesIndexRoute
  '/profile': typeof privateRoutesProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(private-routes)': typeof privateRoutesRouteRouteWithChildren
  '/(public-routes)': typeof publicRoutesRouteRouteWithChildren
  '/(public-routes)/': typeof publicRoutesIndexRoute
  '/(auth-routes)/auth/login': typeof authRoutesAuthLoginRoute
  '/(auth-routes)/auth/register': typeof authRoutesAuthRegisterRoute
  '/(private-routes)/analyses/$analysisId': typeof privateRoutesAnalysesAnalysisIdRoute
  '/(private-routes)/analyses/': typeof privateRoutesAnalysesIndexRoute
  '/(private-routes)/profile/': typeof privateRoutesProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/analyses/$analysisId'
    | '/analyses'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/analyses/$analysisId'
    | '/analyses'
    | '/profile'
  id:
    | '__root__'
    | '/(private-routes)'
    | '/(public-routes)'
    | '/(public-routes)/'
    | '/(auth-routes)/auth/login'
    | '/(auth-routes)/auth/register'
    | '/(private-routes)/analyses/$analysisId'
    | '/(private-routes)/analyses/'
    | '/(private-routes)/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  privateRoutesRouteRoute: typeof privateRoutesRouteRouteWithChildren
  publicRoutesRouteRoute: typeof publicRoutesRouteRouteWithChildren
  authRoutesAuthLoginRoute: typeof authRoutesAuthLoginRoute
  authRoutesAuthRegisterRoute: typeof authRoutesAuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public-routes)': {
      id: '/(public-routes)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicRoutesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private-routes)': {
      id: '/(private-routes)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof privateRoutesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public-routes)/': {
      id: '/(public-routes)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicRoutesIndexRouteImport
      parentRoute: typeof publicRoutesRouteRoute
    }
    '/(private-routes)/profile/': {
      id: '/(private-routes)/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof privateRoutesProfileIndexRouteImport
      parentRoute: typeof privateRoutesRouteRoute
    }
    '/(private-routes)/analyses/': {
      id: '/(private-routes)/analyses/'
      path: '/analyses'
      fullPath: '/analyses'
      preLoaderRoute: typeof privateRoutesAnalysesIndexRouteImport
      parentRoute: typeof privateRoutesRouteRoute
    }
    '/(private-routes)/analyses/$analysisId': {
      id: '/(private-routes)/analyses/$analysisId'
      path: '/analyses/$analysisId'
      fullPath: '/analyses/$analysisId'
      preLoaderRoute: typeof privateRoutesAnalysesAnalysisIdRouteImport
      parentRoute: typeof privateRoutesRouteRoute
    }
    '/(auth-routes)/auth/register': {
      id: '/(auth-routes)/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof authRoutesAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth-routes)/auth/login': {
      id: '/(auth-routes)/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof authRoutesAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface privateRoutesRouteRouteChildren {
  privateRoutesAnalysesAnalysisIdRoute: typeof privateRoutesAnalysesAnalysisIdRoute
  privateRoutesAnalysesIndexRoute: typeof privateRoutesAnalysesIndexRoute
  privateRoutesProfileIndexRoute: typeof privateRoutesProfileIndexRoute
}

const privateRoutesRouteRouteChildren: privateRoutesRouteRouteChildren = {
  privateRoutesAnalysesAnalysisIdRoute: privateRoutesAnalysesAnalysisIdRoute,
  privateRoutesAnalysesIndexRoute: privateRoutesAnalysesIndexRoute,
  privateRoutesProfileIndexRoute: privateRoutesProfileIndexRoute,
}

const privateRoutesRouteRouteWithChildren =
  privateRoutesRouteRoute._addFileChildren(privateRoutesRouteRouteChildren)

interface publicRoutesRouteRouteChildren {
  publicRoutesIndexRoute: typeof publicRoutesIndexRoute
}

const publicRoutesRouteRouteChildren: publicRoutesRouteRouteChildren = {
  publicRoutesIndexRoute: publicRoutesIndexRoute,
}

const publicRoutesRouteRouteWithChildren =
  publicRoutesRouteRoute._addFileChildren(publicRoutesRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  privateRoutesRouteRoute: privateRoutesRouteRouteWithChildren,
  publicRoutesRouteRoute: publicRoutesRouteRouteWithChildren,
  authRoutesAuthLoginRoute: authRoutesAuthLoginRoute,
  authRoutesAuthRegisterRoute: authRoutesAuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
